name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.2 flake8-bandit==2.1.2  bandit==1.7.2 flake8-broken-line==0.3.0 flake8-bugbear==21.11.29 flake8-commas==2.1.0 flake8-comprehensions==3.10.1 flake8-debugger==4.1.2 flake8-docstrings==1.7.0 flake8-eradicate==1.4.0 flake8-isort==4.2.0 flake8-polyfill==1.0.2 flake8-quotes==3.3.2 flake8-rst-docstrings==0.2.7 flake8-string-format==0.3.0
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
    - name: Pytest
      run: pytest

